### ISSUE TITLE
Cleanup the code repo for the TensorFlow Lite image classifier

### ISSUE THREAD

**Issue by georgeslabreche** [georgeslabreche/opssat-smartcam#14]
See the repo's [README](https://github.com/georgeslabreche/tensorflow-opssat-smartcam#what-happened-here) for more details. 

**Todo:**
- [ ] Recreate [the image classifier repo](https://github.com/georgeslabreche/tensorflow-opssat-smartcam) to only host the code required to build and run the image classifier and its TensorFlow Lite C API dependency.
- [ ] Include the image classifier rep as a gitsubmodule inside the SmartCam's repo.
- [ ] Write a build script to build the image classifier and deploy as needed in the SmartCam's bin directory.
